export { createAuthApi } from "./auth";
export { createCatalogApi } from "./catalog";
export { createServicesApi } from "./services";
export { createOrdersApi } from "./orders";
export { createBookingsApi } from "./bookings";
export { createCustomersApi } from "./customers";
export { createStaffApi } from "./staff";
export { createPaymentsApi } from "./payments";
export { createNotificationsApi } from "./notifications";
export { createAnalyticsApi } from "./analytics";
export { createLoyaltyApi } from "./loyalty";
export { createSearchApi } from "./search";
export { createContentApi } from "./content";
export { createLocationsApi } from "./locations";
export { createPortfolioApi } from "./portfolio";
export { createQuotesApi } from "./quotes";
export { createSubscriptionsApi } from "./subscriptions";
export { createTenantsApi } from "./tenants";
export { createDomainsApi } from "./domains";
export { createConfigApi } from "./config";
export { createHealthApi } from "./health";
export { createAuditApi } from "./audit";
export { createDeploymentsApi } from "./deployments";

export type { AuthApi, RegisterParams, RegisterResponse } from "./auth";
export type { CatalogApi } from "./catalog";
export type { ServicesApi, ServiceListResponse } from "./services";
export type { OrdersApi, OrderStatusUpdateParams, RefundParams } from "./orders";
export type { BookingsApi, BookingStatusUpdateParams, RescheduleParams } from "./bookings";
export type { CustomersApi, CustomerListParams, CustomerListResponse, CustomerMetrics } from "./customers";
export type { StaffApi, StaffListResponse, StaffInviteParams } from "./staff";
export type { PaymentsApi, PaymentMethodSummary, AddPaymentMethodParams } from "./payments";
export type { NotificationsApi } from "./notifications";
export type { AnalyticsApi } from "./analytics";
export type { LoyaltyApi, LoyaltyReward } from "./loyalty";
export type { SearchApi } from "./search";
export type { ContentApi, ContentListParams, ContentListResponse } from "./content";
export type { LocationsApi, LocationRecord, CreateLocationParams, UpdateLocationParams, LocationListParams, LocationListResponse } from "./locations";
export type { PortfolioApi } from "./portfolio";
export type { QuotesApi } from "./quotes";
export type { SubscriptionsApi, SubscriptionListResponse, TenantSubscriptionRecord, CreateSubscriptionParams } from "./subscriptions";
export type { TenantsApi, TenantListParams, TenantListResponse, ImpersonateResponse } from "./tenants";
export type { DomainsApi, DomainListResponse, CreateDomainParams, DomainVerifyResponse } from "./domains";
export type { ConfigApi, GlobalConfig } from "./config";
export type { HealthApi, HealthStatus, JobStatus } from "./health";
export type { AuditApi, AuditListParams, AuditListResponse } from "./audit";
export type { DeploymentsApi, DeploymentRecord, DeploymentListParams, DeploymentListResponse, TriggerDeploymentParams } from "./deployments";
